artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Jakee4488/DataSets/raw/refs/heads/main/GDP_Data_Set.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/quarterly_GDP.csv
  STATUS_FILE: artifacts/data_validation/status.txt